# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - todos-app

on:
  push:
    branches:
      - master
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: 'Set up Node.js version'
#      uses: actions/setup-node@v1
#      with:
#        node-version: '14.x'
#
#    - name: 'npm install, build, and test'
#      run: |
#        npm install
#        npm run build --if-present
#        npm run test --if-present
#
#    - name: 'Zip files'
#      run:  zip -r -T -q node_app.zip .
#
#    - name: 'Display structure of uploading files'
#      run: ls
#
#    - name: 'Upload artifact for deployment job'
#      uses: actions/upload-artifact@v2
#      with:
#        name: node-app
#        path: node_app.zip
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#    - name: 'Download artifact from build job'
#      uses: actions/download-artifact@v2
#      with:
#        name: node-app
#    - name: 'Display structure of downloaded files'
#      run: ls
#    - name: 'Deploy to Azure Web App'
#      id: deploy-to-webapp
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'cosmos-todos'
#        slot-name: 'production'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d1f872f2bc25403bb25ab17231fa6d7f }}
#        package: .

env:
  AZURE_WEBAPP_NAME: cosmos-todos    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use
#
#jobs:
#  build-and-deploy:
#    name: Build and Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Use Node.js ${{ env.NODE_VERSION }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: npm install, build, and test
#        run: |
#          # Build and test the project, then
#          # deploy to Azure Web App.
#          npm install
#          npm run build --if-present
#          npm run test --if-present
#      - name: 'Deploy to Azure WebApp'
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          slot-name: 'production'
#          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d1f872f2bc25403bb25ab17231fa6d7f }}
#          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
#


#env:
#  AZURE_WEBAPP_NAME: node-gh-accelerator   # set this to your application's name
#  AZURE_WEBAPP_PACKAGE_PATH: "application"      # set this to the path to your web app project, defaults to the repository root
#  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build:
    name: Build Node App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Build and test the project
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Creating artifact directories
        run: |
          mkdir buildartifacts
      # Archive build artifact
      - name: Archive Application
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./buildartifacts/application.zip .
      # Uploading application to build artifact
      - name: Upload Application to Build Artifact
        continue-on-error: false
        uses: actions/upload-artifact@v2
        with:
          name: buildartifacts
          path: buildartifacts
  deploy:
    name: Deploy to azure web app
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Downloading build artifact
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        continue-on-error: false
        with:
          name: buildartifacts
          path: buildartifacts
      # Uzipping build artifacts
      - name: unzipping build artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: unzip -qq ./buildartifacts/application.zip -d .

      # Deploy Node app to Azure
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d1f872f2bc25403bb25ab17231fa6d7f }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
